---

- name: Install serial communication programs
  ansible.builtin.apt:
    pkg: "{{ serial_packages }}"
    state: present

- name: Configure minicom
  ansible.builtin.import_tasks: minicom.yml
  when: "minicom_minirc | length >= 1"
