---

- name: Install serial communication programs
  apt:
    pkg: "{{ serial_packages }}"
    state: present

- name: Configure minicom
  ansible.builtin.import_tasks:
    file: minicom.yml
  when: "minicom_minirc | length >= 1"
